name: Publish
on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  deploy:
    runs-on: ubuntu-latest
    needs: cleanup
    permissions:
      contents: write  # To push a branch
      pull-requests: write  # To create a PR from that branch
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install libraries
      run: pip install mkdocs mkdocs-material pymdown-extensions mkdocs-material-extensions mkdocs-static-i18n cairosvg pillow

    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    - run: cp -rf CNAME docs/

    - run: mkdocs gh-deploy --force
